# Fetching the latest node image on alpine linux
FROM node:alpine AS development

RUN npm install -g create-react-app

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /react-app

# Installing dependencies
COPY ./frontend/package.json /react-app
RUN npm install

# Copying all the files in our project
COPY frontend .

# Starting our application
CMD npm start